import pandas as pd
import streamlit as st

# Page Configuration
st.set_page_config(
    page_title="GeoMine Intelligence | SIH26023 MVP", page_icon="⛏️", layout="wide"
)

# Initialize Session State
if "records" not in st.session_state:
  st.session_state.records = [
      {
          "record_id": "BH-001",
          "location": "East Block",
          "depth_m": 120,
          "rock_type": "Shale",
          "grade_pct": 0.42,
          "notes": "Fractured core noted; assay verified",
      },
      {
          "record_id": "BH-002",
          "location": "East Block",
          "depth_m": 145,
          "rock_type": "Sandstone",
          "grade_pct": None,
          "notes": "Sample assay pending",
      },
      {
          "record_id": "BH-003",
          "location": "North Ridge",
          "depth_m": 98,
          "rock_type": "Limestone",
          "grade_pct": 0.18,
          "notes": "Lithology logged; sample label requires review",
      },
  ]

if "reports_count" not in st.session_state:
  st.session_state.reports_count = 2

# Sidebar Navigation
st.sidebar.title("GeoMine Intelligence")
st.sidebar.caption("Reporting workspace · SIH26023")

page = st.sidebar.radio(
    "WORKSPACE",
    [
        "Overview",
        "Data & Documents",
        "Report Studio",
        "Ask Your Data",
        "Review & Audit Trail",
    ],
)

# Helper function to convert records to DataFrame
def get_df():
  return pd.DataFrame(st.session_state.records)


# ----------------------------------------------------
# 1. OVERVIEW PAGE
# ----------------------------------------------------
if page == "Overview":
  st.title("Mining reports, from raw data to review-ready.")
  st.write(
      "A unified workspace to structure geological and mining inputs, flag"
      " data-quality issues, draft consistent reports, and keep every finding"
      " traceable to its source."
  )

  df = get_df()
  total_records = len(df)
  missing_count = df.isna().sum().sum()
  total_cells = df.size if total_records > 0 else 1
  completeness = (
      int((1 - missing_count / total_cells) * 100) if total_records > 0 else 0
  )

  col1, col2, col3, col4 = st.columns(4)
  col1.metric("Sources loaded", "3", "Sample dataset")
  col2.metric("Records analysed", total_records)
  col3.metric("Items needing review", len(df[df.isna().any(axis=1)]))
  col4.metric("Draft reports", st.session_state.reports_count)

  st.subheader("Operational overview")
  st.info("Illustrative sample project: East Block exploration")
  st.progress(
      completeness / 100,
      text=f"Source validation coverage: {completeness}%",
  )

# ----------------------------------------------------
# 2. DATA & DOCUMENTS PAGE
# ----------------------------------------------------
elif page == "Data & Documents":
  st.title("Data Intake")
  st.write("Upload source files or inspect current records.")

  uploaded_file = st.file_uploader(
      "Choose a file", type=["csv", "json", "xlsx", "txt"]
  )
  if uploaded_file is not None:
    if uploaded_file.name.endswith(".csv"):
      new_df = pd.read_csv(uploaded_file)
      st.session_state.records = new_df.to_dict(orient="records")
      st.success(f"Successfully loaded {len(new_df)} records from CSV!")

  st.subheader("Loaded Records")
  df = get_df()
  st.dataframe(df, use_container_width=True)

  if st.button("Clear Imported Records"):
    st.session_state.records = []
    st.rerun()

# ----------------------------------------------------
# 3. REPORT STUDIO PAGE
# ----------------------------------------------------
elif page == "Report Studio":
  st.title("Report Studio")
  st.write("Generate a review-ready report draft from loaded records.")

  report_title = st.text_input(
      "Report Title", "Geological Observation and Data Quality Report"
  )
  project_name = st.text_input("Project / Block", "East Block Exploration")
  period = st.text_input("Reporting period", "Q2 2026")
  prepared_by = st.text_input("Prepared by", "SIH26023 Team")

  if st.button("Generate Report Draft"):
    df = get_df()
    report_text = f"""{report_title.upper()}
========================================
Project: {project_name}
Period: {period}
Prepared by: {prepared_by}

1. EXECUTIVE SUMMARY
Summarizing {len(df)} loaded record(s). Findings are preliminary and require expert validation.

2. OBSERVATIONS SUMMARY
- Total records evaluated: {len(df)}
- Columns present: {list(df.columns) if not df.empty else 'None'}

Generated by GeoMine Intelligence (SIH26023 MVP).
"""
    st.session_state.reports_count += 1
    st.text_area("Generated Report Output", report_text, height=300)
    st.download_button(
        "Download Report (.txt)", report_text, file_name="geomine-report.txt"
    )

# ----------------------------------------------------
# 4. ASK YOUR DATA PAGE
# ----------------------------------------------------
elif page == "Ask Your Data":
  st.title("Ask Your Data")
  st.write("Search through loaded records using keywords.")

  query = st.text_input(
      "Question",
      placeholder="e.g., Which records have missing assay values?",
  )
  if query:
    df = get_df()
    # Simple keyword search
    results = df[
        df.astype(str)
        .apply(lambda x: x.str.contains(query, case=False, na=False))
        .any(axis=1)
    ]
    st.write(f"Found {len(results)} matching records:")
    st.dataframe(results, use_container_width=True)

# ----------------------------------------------------
# 5. REVIEW & AUDIT TRAIL PAGE
# ----------------------------------------------------
elif page == "Review & Audit Trail":
  st.title("Review & Audit Trail")
  st.write("Review data quality flags and track status.")

  df = get_df()
  flags = []
  if not df.empty:
    for idx, row in df.iterrows():
      for col, val in row.items():
        if pd.isna(val) or str(val).strip() == "":
          flags.append({
              "Record": row.get(
                  "record_id", f"Row {idx+1}"
              ),
              "Issue": f"Missing value in field: {col}",
              "Action": f"Verify {col} against field sheet.",
              "Status": "Needs review",
          })

  if flags:
    flags_df = pd.DataFrame(flags)
    st.dataframe(flags_df, use_container_width=True)
  else:
    st.success("No review flags detected in current dataset!")
